# Generated by Django 5.0.6 on 2024-08-21 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['date'],
            },
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name'], 'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title'], 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='reader',
            options={'ordering': ['name'], 'verbose_name': 'Reader', 'verbose_name_plural': 'Readers'},
        ),
        migrations.AlterModelOptions(
            name='reading',
            options={'ordering': ['start_date'], 'verbose_name': 'Reading', 'verbose_name_plural': 'Readings'},
        ),
        migrations.AlterUniqueTogether(
            name='reading',
            unique_together={('reader', 'book', 'start_date')},
        ),
        migrations.CreateModel(
            name='SpecialReadingEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bboard.event')),
                ('extra_notes', models.TextField(blank=True, null=True)),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_events', to='bboard.reading')),
            ],
            options={
                'verbose_name': 'Special Reading Event',
                'verbose_name_plural': 'Special Reading Events',
                'ordering': ['date'],
            },
            bases=('bboard.event',),
        ),
    ]
